---
- name: service restart nginx
  tags: nginx
  become: "{{ nginx_become_enable }}"
  when: not nginx_config_only
  service:
    state: restarted
    name: nginx

- name: service reload nginx
  tags: nginx
  become: "{{ nginx_become_enable }}"
  when: not nginx_config_only
  service:
    state: reloaded
    name: nginx
