---
# handlers file for ansible-nginx
- name: restart nginx
  tags: nginx
  become: true
  service: name=nginx state=restarted

- name: reload nginx
  tags: nginx
  become: true
  service: name=nginx state=reloaded
